EmployeeManagementCore/EmployeeManagement.API/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeManagement.Models.Employees;
using EmployeesManagement.BAL.Repository.EmployeeRepository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class EmployeesController : ControllerBase
    {
        private readonly IEmployeeRepository _employeeRepository;
        public EmployeesController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }
        
        [HttpGet]
        [Route("/GetEmployees")]
        public async Task<IActionResult> GetEmployeesAsync()
        {
            try
            {

                var employees = await _employeeRepository.GetAllEmployeeAsync();

                return Ok(employees);

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }


        [HttpGet]
        [Route("/GetEmployee/{id}")]
        public async Task<IActionResult> GetEmployeeByIdAsync(int id)
        {
            try
            {

                var employee = await _employeeRepository.GetEmployeeAsync(id);

                return Ok(employee);

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        [Route("/CreateEmployee")]
        public async Task<IActionResult> CreateEmployeeAsync(Employee employee)
        {
            try
            {
                var result = await _employeeRepository.CreateEmployeeAsync(employee);

                return Ok(result);

            }
            catch (Exception)
            {

                throw;
            }
        }

        // PUT: api/Employee/5
        [HttpPut]
        [Route("/UpdateEmployee/{id}")]
        public async Task<IActionResult> UpdateEmployeeAsync(int id, [FromBody] Employee employee)
        {
            try
            {
                var result = await _employeeRepository.UpdateEmployeeAsync(id, employee);
                if (result.ContainsKey(true))
                {
                    return Ok(result[true]);
                }

                else if (result[false] == "No Record Found")
                {
                    return NotFound(result[false]);
                }
                else
                {
                    return new BadRequestResult();
                }

            }
            catch (Exception)
            {

                throw;
            }
        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete]
        [Route("/DeleteEmployee/{id}")]
        public async Task<IActionResult> DeleteEmployeeAsync(int id)
        {
            try
            {
                var result = await _employeeRepository.DeleteEmployeeAsync(id);
                if (result.ContainsKey(true))
                {
                    return Ok(result[true]);
                }

                else if (result[false] == "No Record Found")
                {
                    return NotFound(result[false]);
                }
                else
                {
                    return new BadRequestResult();
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }



    }
}

EmployeeManagementCore/EmployeeManagement.API/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class HomeController : ControllerBase
    {
        [HttpGet]
        [Route("/")]
        public ContentResult  GetSwagger()
        {
            string baseUrl= HttpContext.Request.GetDisplayUrl();
            string swaggerUrl = baseUrl + "swagger/index.html"; 

            string link="<h2><a href='"+swaggerUrl+"'>Go to Swagger</a></h2>";


            return new ContentResult
            {
                ContentType = "text/html",
                Content = link
            }; 


        }
    }
}

EmployeeManagementCore/EmployeeManagement.API/Controllers/SwaggerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.API.Controllers
{
    [Route("[controller]")]
    public class SwaggerController : Controller
    {
        [HttpGet]
        [Route("/Swagger")]
        public IActionResult GetSwagger()
        {

            string baseUrl = HttpContext.Request.GetDisplayUrl();
            string swaggerUrl = baseUrl + "/index.html";

            return Redirect(swaggerUrl);
            
        }
    }
}

EmployeeManagementCore/EmployeeManagement.API/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

EmployeeManagementCore/EmployeeManagement.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    </environment>



</head>
<body style="background:#ef66a1">

    <div>
       

        @{
            await Html.RenderPartialAsync("_NavigationPartial");
        }

    </div>

    <div>
        @RenderBody()
    </div>
</body>
</html>

EmployeeManagementCore/EmployeeManagement.API/Views/Shared/_NavigationPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a asp-controller="Swagger" asp-action="GetSwagger" class="nav-link">Swagger</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>